Script is now checking if cmake is even installed

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -23,6 +23,15 @@ SET_PREFIX=0
 SET_CC=0
 SET_CXX=0
 
+#check if cmake is installed
+CMAKE_PATH=`which cmake`
+if [ $? -eq 0 ]; then
+	echo "Found cmake at $CMAKE_PATH"
+else
+	echo "Could not find cmake executable"
+	exit 1
+fi
+
 #Read arguments
 for arg in $@; do
 	#seperate key=value pairs
